### ISSUE TITLE
Fix request for some symbols in Kantenji mode

### ISSUE THREAD

**Issue by brlat** [uhyo/tenji#1]
すばらしいアプリの公開ありがとうございます。私は漢点字ユーザーです。現状でもとても便利です。ニュースなどを漢点字に変換して読んでいます。

漢点字モードでの次の記号の変換の変更を希望します。6点点字と漢点字の6点の位置がずれているためのものです。

- .(ピリオド) - 6点点字⠲(2 5 6の点)→漢点字(⢤(3 6 8の点)
- /(スラッシュ) - 6点点字⠌(3 4の点)→漢点字(5 7の点)⡐
- :(コロン) - 6点点字⠒(2 5の点)→漢点字⠤(3 6の点)
- …(テンテンテン) - 6点点字⠲⠲⠲(2 5 6の点3つ)→6点点字(空白)⠂⠂⠂(空白)(2の点3つ)→漢点字(空白)⠄⠄⠄(空白)(3の点3つ)

ありがとうございます

**Comment by uhyo** [comment]
ご報告いただき、ありがとうございます。
ご指摘いただいた点を修正しました。
