### ISSUE TITLE
Unicode点字変換にて、点字「⠰⠀⠡」（読点-全角スペース-清音）を［↑点字から変換↑］すると、「、が」（読点-濁音）に変換されます。

### ISSUE THREAD

**Issue by ghost** [uhyo/tenji#2]

**Comment by ghost** [comment]
GitHubの初心者のため、基本的な使い方も分かっておらずissueを汚してしまい、申し訳ありません。
素晴らしいツール、Unicode点字変換 https://uhyo.github.io/tenji-web/ を公開いただきありがとうございます。

Unicode点字変換 にて、
1. 下段の「ここに点字を入力」欄に、点字「⠰⠀⠡」（読点-全角スペース-清音）を入力し
2. ［↑点字から変換↑］ボタンをクリックすると、
3. 上段の「ここに日本語を入力」欄で「、が」（読点-濁音）に変換されます。

例：点字（読点-全角スペース-清音）を入力し、
⠰⠀⠡⠰⠀⠣⠰⠀⠩⠰⠀⠫⠰⠀⠪⠀
⠰⠀⠱⠰⠀⠳⠰⠀⠹⠰⠀⠻⠰⠀⠺
⠰⠀⠕⠰⠀⠗⠰⠀⠝⠰⠀⠟⠰⠀⠞
⠰⠀⠥⠰⠀⠧⠰⠀⠭⠰⠀⠯⠰⠀⠮
［↑点字から変換↑］をクリックすると、
下記の文字（読点-濁音）に変換されます。
、が、ぎ、ぐ、げ、ご 
、ざ、じ、ず、ぜ、ぞ
、だ、ぢ、づ、で、ど
、ば、び、ぶ、べ、ぼ

**Comment by uhyo** [comment]
ご報告いただきありがとうございます。反応が遅くなり申し訳ありません。
こちらは修正しました。

**Comment by ghost** [comment]
ご対応頂きありがとうございます。こちらこそ、お礼が遅くなり申し訳ありません。
今後も「Unicode点字変換」を利用させて頂きます。
