### ISSUE TITLE
囲み記号（カギ類・カッコ類）と英大文字の変換について

### ISSUE THREAD

**Issue by takemae-nct** [uhyo/tenji#3]
私は視覚障害者向けのハザードマップを作成しています。指定緊急避難場所を点字翻訳する際に、Unicode点字変換（https://uhyo.github.io/tenji-web/ ）を利用させていただいております。ありがとうございます。
さて、その中で２つ不具合がありましたので、改善して頂けると大変助かります。
１つ目は、囲み記号のカッコ類の点字への変換です。第１カッコで変換されなければならないところで第２カッコで変換されています。点字の規則としては、第１カッコを用いることを基本とし、その中にさらにカッコ類が必要であれば、二重カッコを用います。また、二重カッコと区別して他のカッコを必要とする場合に、第２カッコを用います。カギ類の変換も同じ問題があります。
２つ目は、英大文字が続く単語の点字への変換です。「外字符」の後に１文字１文字に「大文字符」が付いて変換されますが、「外字符」の後に「二重大文字符」を付けて英字を変換する方がマス数が少なくなり障害者から喜ばれます。
これら２点を改善して頂けると大変助かります。よろしくお願いします。

**Comment by uhyo** [comment]
こちらのご連絡ありがとうございました。
カッコとカギ類の変換の問題は第一括弧・第一カギに変換されるように修正しました。また、二重大文字符を必要に応じて使用するように変換を修正しました。

**Comment by takemae-nct** [comment]
お忙しい中、ご対応ありがとうございました。
大変助かります。
